In [7]:
import pandas as pd
from datetime import datetime, timedelta

from recommenders.datasets.download_utils import maybe_download
from recommenders.datasets.python_splitters import (
    python_random_split,
    python_chrono_split,
    python_stratified_split
)

In [9]:
DATA_URL = "https://files.grouplens.org/datasets/movielens/ml-100k/u.data"
DATA_PATH = "ml-100k.data"

COL_USER = "UserId"
COL_ITEM = "MovieId"
COL_RATING = "Rating"
COL_TIMESTAMP = "Timestamp"

In [10]:
filepath = maybe_download(DATA_URL, DATA_PATH)

100%|██████████| 1.93k/1.93k [00:00<00:00, 7.16kKB/s]

In [21]:
data = pd.read_csv(filepath , sep="\t", names=[COL_USER, COL_ITEM, COL_RATING,COL_TIMESTAMP])

In [22]:
data.head()

   UserId  MovieId  Rating  Timestamp
0     196      242       3  881250949
1     186      302       3  891717742
2      22      377       1  878887116
3     244       51       2  880606923
4     166      346       1  886397596

In [14]:
data.describe()

             UserId        MovieId         Rating     Timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08

In [23]:
print(
    "Total number of ratings: {}".format(data.shape[0]),
    "Total number of users are:{}".format(data[COL_USER].nunique()),
    "Total number of items are:{}".format(data[COL_ITEM].nunique()) 

)

Total number of ratings: 100000 Total number of users are:943 Total number of items are:1682

In [24]:

data[COL_TIMESTAMP] = data.apply(
    lambda x:datetime.strftime(datetime(1970,1,1,0,0,0) + timedelta(seconds=x[COL_TIMESTAMP].item()),"%Y-%m-%d %H:%M:%S") ,
    axis = 1)

In [25]:
data.head()

   UserId  MovieId  Rating            Timestamp
0     196      242       3  1997-12-04 15:55:49
1     186      302       3  1998-04-04 19:22:22
2      22      377       1  1997-11-07 07:18:36
3     244       51       2  1997-11-27 05:02:03
4     166      346       1  1998-02-02 05:33:16

In [26]:
#Random Split
data_train, data_test = python_random_split(data,ratio=0.7)

In [27]:
data_train.shape[0] , data_test.shape[0]

(70000, 30000)

In [ ]:
#multisplit 
data_train, data_validate, data_test = python_random_split(data, ratio=[0.6,0.2,0.2])

c:\Users\muzic\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\_core\fromnumeric.py:57: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [29]:
data_train.shape[0] , data_validate.shape[0],data_test.shape[0]

(60000, 20000, 20000)

In [30]:
#chronological split by user

data_train, data_test = python_chrono_split(
    data, ratio = 0.7, filter_by="user",
    col_user = COL_USER, col_item = COL_ITEM, col_timestamp=COL_TIMESTAMP
)

In [32]:
data_train[data_train[COL_USER]==2].tail(10)

       UserId  MovieId  Rating            Timestamp
37408       2       25       4  1998-02-27 03:54:08
16230       2      279       4  1998-02-27 03:55:45
21631       2      111       4  1998-02-27 03:57:33
28341       2       14       4  1998-02-27 03:57:33
39562       2       10       2  1998-02-27 03:57:33
7973        2       13       4  1998-02-27 03:58:42
20534       2      282       4  1998-02-27 03:58:42
46011       2      284       4  1998-02-27 04:00:17
52964       2      237       4  1998-02-27 04:00:17
924         2      251       5  1998-02-27 04:01:24

In [33]:
data_train[data_train[COL_USER] == 2].head(10)

       UserId  MovieId  Rating            Timestamp
85606       2      286       4  1998-02-27 03:26:00
21902       2      258       3  1998-02-27 03:26:01
27695       2      305       3  1998-02-27 03:27:45
10683       2      307       3  1998-02-27 03:27:46
77906       2      288       3  1998-02-27 03:30:52
6310        2      312       3  1998-02-27 03:37:11
16025       2      301       4  1998-02-27 03:37:11
700         2      292       4  1998-02-27 03:39:34
9201        2      303       4  1998-02-27 03:39:34
13440       2      315       1  1998-02-27 03:39:34

In [ ]:
#min rating is applied to data so that there is sufficient number of ratings for user/item in the data